server:
    port: 8080

spring:
    datasource:
        url: jdbc:postgresql://203.57.85.21:5432/iotroot?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: org.postgresql.Driver
        username: iotroot_app
        password: av2025@IOTROOT
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC

mqtt:
    broker:
        url: tcp://astraval.com:1883   # ssl://astraval.com:8883
        username: user1
        password: password1
        client-id: client1
        keep-alive: 60
        connection-timeout: 30
        automatic-reconnect: true
        topic: iet/#
        clean-session: false
        
        
logging:
    level:
        root: WARN
        com.astraval.iotroot: INFO
